<?php

/**
 * Implements hook_field_formatter_info().
 */
function ctn_kitchen_sink_field_formatter_info() {
  return array(
    'ctn_video_tag_formatter' => array( //Machine name of the formatter
      'label' => t('Video Tag'),
      'field types' => array('file'), //This will only be available to text fields
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function ctn_kitchen_sink_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  drupal_add_library('mediaelement', 'mediaelement');
  $element = array(); // Initialize the var
  if(!empty($items)) {
    $element[0]['#markup'] = '<video controls width="100%" height="100%" src="http://d31f43pj6hfv5.cloudfront.net/mp4/' . $items[0]['filename'] .                       '">Your Browser does not support html5 video</video>' .
                           '<script>jQuery(\'video\').mediaelementplayer();</script>';
  }
  return $element;
}

function ctn_kitchen_sink_library() {
  $path = libraries_get_path('mediaelement');
  $libraries = array();

  $libraries['mediaelement'] = array(
    'title' => 'Media Element',
    'website' => 'http://mediaelementjs.com/',
    'version' => '2.1.6',
    'js' => array(
      // The mediaelement script detects the path to itself to call other files
      // in the same location. With preprocessing this is problematic as the
      // script is no longer in the same directory as its other assets. There
      // is an option that can be passed into the script with its location.
      // @todo Update all calls to mediaelement to pass in the assets location.
      $path . '/build/mediaelement-and-player.min.js' => array('group' => JS_LIBRARY, 'preprocess' => FALSE),
    ),
    'css' => array(
      $path . '/build/mediaelementplayer.min.css' => array('group' => CSS_SYSTEM),
    ),
  );
  return $libraries;
}

function ctn_kitchen_sink_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
  }
}

/**
 * Implements hook_query_alter().
 */
function ctn_kitchen_sink_query_alter($query) {
  if ($query->hasTag('node_export_features')) {
    $condition = db_or()->condition('type', 'page')->condition('type', 'webform');
    $query->condition($condition);
  }
}

function ctn_kitchen_sink_node_export_node_import_alter(&$node, $original_node, $save) {
  $path = 'node/' . $node->nid;
  if (drupal_get_path_alias($path) != $path) {
    $node->menu = NULL;
    $node->path = NULL;
  }
}

function ctn_kitchen_sink_file_formatter_info_alter(&$info) {
  $info['media_youtube_video']['file types'][] = 'ctn_member_video';
}