<?php

function ctn_vod_cron() {

  //This is kinda expensive only do it every few hours.
  $last_run = variable_get('ctn_vod_cron_last_run', 0);
  $difference = time() - $last_run;
  $six_hours = 60 * 60 * 6;

  if($difference < $six_hours) {
    return;
  }
  variable_set('ctn_vod_cron_last_run', time());
  
  //Get the files that are on ctns servers.
	$server = 'http://video.ctn5.org';
  $response = drupal_http_request($server);
  $vods = drupal_json_decode($response->data);


  foreach ($vods as $vod) {
    $parts = explode('.', $vod);
    $show_id = intval($parts[0]);

    $sql = 'SELECT entity_id FROM {field_data_cablecast_show_id} cc WHERE cc.cablecast_show_id_value = :show_id';

    $nid = db_query($sql, array(':show_id' => $show_id))->fetchField();
    if($nid) {
      $files = entity_load('file', FALSE, array('uri' => $server . '/mp4/' . $vod), TRUE);
      $file = !empty($files) ? reset($files) : FALSE;
      if(!$file) {
        $file = remote_stream_wrapper_file_create_by_uri($server . '/mp4/' . $vod);
        file_save($file);
      }
      $show = node_load($nid, NULL, TRUE);
      if($show->ctn_vod_file['und'][0]['fid'] != $file->fid) {
        $show->ctn_vod_file['und'][0]['fid'] = $file->fid;
        $show->ctn_vod_file['und'][0]['display'] = 1;
        node_save($show);
      }
    }
  }
}