<?php
function ctn_front_page_block_test() {
	$sql = 'SELECT name FROM {views_view} vv WHERE vv.tag LIKE :view_tag';
	$viewNames = db_query($sql, array(":view_tag" => '%' . db_like('ctn-front-page') . '%'))->fetchAll();

	foreach($viewNames as $name) {
		$view = views_get_view($name->name);
		$view->execute();
	}
}

function ctn_front_page_block_block_info() {
	$blocks = array();
	$blocks['ctn_front_page'] = array(
		'info' => t('CTN Front Page')
	);

	return $blocks;
}

function ctn_front_page_block_block_view($delta) {
	return ctn_front_page_block_render();

}

function ctn_front_page_block_render() {
	$output = '';
	$views = views_get_enabled_views();
	foreach($views as $view) {
		if(preg_match('/ctn-front-page/', $view->tag)) {
			//$view->execute();
			$output = $output . $view->preview('panel_pane_1');
		}
	}

	return array('subject' => NULL, 'content' => $output);
}

function ctn_front_page_block_views_api() {
  return array(
    'api' => 3,
  );
}

function ctn_front_page_block_views_query_alter(&$view, &$query) {
  if (preg_match('/^front_page_.+/', $view->name)) {
    $query->where[0]['type'] = 'OR';
  }
}